---
title: "If You (Re)Build It, Will They Come? Evidence from California"
author: "Presenter: Zach Levin, Federal Trade Commission\n Discussant: Ian McCarthy, Emory University and NBER"
institute: "MHEC, September 7, 2023"
format: 
  revealjs:
    theme: [simple, quarto-styles.scss]
    preview-links: auto
    chalkboard:
      boardmarker-width: 5
    slide-number: true
#    embed-resources: true
from: markdown+emoji
execute: 
  echo: false
---

```{r}
#| include: false
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, lubridate, scales, hrbrthemes, gdata, ggforce, gganimate)
```

---

## Background {.section-divider}

---

### Research Question

What happens after construction of a new hospital?

- Utilization at focal hospital versus other hospitals in the market
- Quality changes, clinical and non-clinical

---

### Relevant Literatures

1. Entry and competition in hospital markets
2. Patient preferences for clinical quality versus amenities
3. Non-profit hospitals and incentives for overuse?

---

### 1. Entry and Competition

- **Mid 1960s:** Increasing concern about hospital costs and excess capacity, duplicative services and facilities
- **1964:** New York State enacts the first certificate of need (CON) program
- **1974:** National Health Planning and Resources Development Act requires all states to have CON programs
- **1980:** CON laws in place for all states except Louisiana

::: {.fragment}
Enacted during cost-plus reimbursement, where hospitals had little incentive to control costs
:::

---

### 1. Entry and Competition

- **1986:** Congress repeals the National Health Planning and Resources Development Act
- **1990s:** Many states repeal or weaken CON laws
- **Today:** 35 states and the District of Columbia still have some form of CON laws, 14 states have CON laws that apply specifically to hospitals

::: {.fragment}
As a binding barrier to entry, CON often cited as part of the hospital pricing problem
:::


---

### 2. Patient Preferences

- Strong evidence that patients value non-clinical quality
- Construction implies shiny new buildings, private rooms, etc.

---

### 3. Non-profit Hospitals

- Possible to link construction with NFP status?
- Reinvesting profits back into system (as necessary for NFP status) may over-incentivize construction
- Policy implications re NFP status if such construction is "wasteful"
- Potential call for more oversight of tax benefits

---

## What does this paper do? {.section-divider}

---

### Basic Idea

- **2006:** California enacts SB 1953, requiring all hospitals to meet seismic safety standards by 2030
  - 90% of hospitals did not meet these standards in 2006
- **2009-2015:** 41 non-ED expansions or rebuilds

---

### Empirical Strategy

Stacked difference-in-differences

  - Treatment: hospital in California that expands or rebuilds in 2009-2015
  - Control: hospitals in other markets (20+ miles away) that do not expand or rebuild
  - Time: pre- and post-construction

---

### Findings

- Construction projects yield 10%+ increase in admissions
- Patients more likely to recommend hospitals after construction
- No evidence of changes in clinical quality

---

## Some Conceptual Questions {.section-divider}

---

### Implications for CON Laws?

- In what ways are CON laws binding?
  - Own-hospital expansion? (seems unlikely)
  - Entry by new hospitals? (seems more likely)

---

### Implications for Amenities?

- Large capital investments imply investment in amenities
- Can this be measured directly?
- Is "room always quite" or "always respond quickly" an amenity?

---

## Some Empirical Questions {.section-divider}

---

### Why did the hospitals expand or rebuild?

> ...though I am unable to differentiate whether this growth is a response to unmet needs.


::: {.fragment}
**Things to consider:**
  
  - Pre-construction occupancy to identify capacity constrained vs. unconstrained hospitals (by admission category)
  - Admission or procedure codes before/after construction to identify services that expanded
:::


