---
title: "The Effect of Physician Group Mergers on the Health Outcomes of Medicare Beneficiaries"
subtitle: "Presenter: Brett Wendling"
author: "Discussant: Ian McCarthy"
date: "SHESG Annual Meeting, October 8, 2021"
header-includes: 
  - \usepackage{graphicx}
  - \usepackage{amsmath}
  - \usepackage{includepdf}
output:
#  html_document: default (toggle on for "simplified" view)
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: ["macros.js","https://platform.twitter.com/widgets.js"]
#knit: pagedown::chrome_print
---

<!-- Adjust some CSS code for font size, maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(dplyr.summarise.inform = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes,scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD, ggrepel, xaringanExtra, webshot)
```


```{r xaringan-scribble, echo=FALSE}
xaringanExtra::use_scribble(rgb(0.9, 0.5, 0.5))
```

# Changing physician landscape

```{r}
phy.status <- tribble(
  ~"Status", ~"2012", ~"2014", ~"2016", ~"2018",
  "Owner", 53.2, 50.8, 47.1, 45.9,
  "Employee", 41.8, 43.0, 47.1, 47.4,
  "Independent", 5.0, 6.2, 5.9, 6.7
)

phy.practice <- tribble(
  ~"Type", ~"2012", ~"2014", ~"2016", ~"2018",
  "Solo", 18.4, 17.1, 16.5, 14.8,
  "Single Specialty", 45.5, 42.2, 42.8, 42.8,
  "Multi Specialty", 22.1, 24.7, 24.6, 25.2,
  "Hospital", 5.6, 7.2, 7.4, 8.0,
  "Faculty", 2.7, 2.8, 3.1, 3.0,
  "Other", 5.7, 5.9, 5.7, 6.2
)

phy.size <- tribble(
  ~"Size", ~"2012", ~"2014", ~"2016", ~"2018",
  "Less than 5", 40.0, 40.9, 37.9, 35.7,
  "5 to 10", 21.4, 19.8, 19.9, 20.8,
  "11 to 24", 13.4, 12.1, 13.3, 12.7,
  "25 to 49", 7.1, 6.3, 7.4, 7.6,
  "50 or more", 12.2, 13.5, 13.8, 14.7,
)
```
